config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home'

  #resources :recipes  
  get '/recipes', to: 'recipes#index'
  get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  post '/recipes', to: 'recipes#create'
  get 'recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
  patch '/recipes/:id', to: 'recipes#update'
  get 'recipes/:id', to: 'recipes#show', as: 'recipe'
  delete 'recipes/:id', to: 'recipes#destroy'
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_RAGES = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                                    uniqueness: { case_sensitive: false },
                                    format: { with: VALID_EMAIL_RAGES }
                                    
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  mount_uploader :picture, PictureUploader
  # validates :picture_size
  
  
  # private
  
  #   def picture_size
  #     if picture_size > 10.megabytes
  #       errors.add(:picture, 'Shoud be less than 10MB')
  #     end
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  
  def index
    @recipes = Recipe.all.order('created_at DESC')
  end
  
  def show
      # @recipe = Recipe.find(params[:id])
  end
  
  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.find(1)
    
    if @recipe.save
      flash[:success] = "Recipe was successfully created."
      redirect_to @recipe
    else 
      render :new
    end
   
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was successfully updated."
      redirect_to @recipe
    else 
      render 'edit'
    end
  end
  
  def destroy
  end
  
  
  
  private
  
  def recipe_params
    params.require(:recipe).permit(:name, :summary, :description, :picture)
  end
    
  
  def find_recipe
    @recipe = Recipe.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p> &copy My Recipe App . All Rights reserved.</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %>
      <a class="close" data-dismiss='alert'>&#215</a>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
 <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'myRecipes', root_path, class: 'navbar-brand', id: 'logo' %>
      </div>


  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'All Recipes', recipes_path, class: '' %></li>
        <li><%= link_to 'New Recipe', new_recipe_path, class: '' %></li>
        <li><%= link_to 'l1', '', class: '' %></li>
        <li><%= link_to 'l1', '', class: '' %></li>
      </ul>       
            
    
    
      
      <!--<ul class="nav navbar-nav navbar-right">-->
      <!--  <li><a href="#">Link</a></li>-->
      <!--  <li class="dropdown">-->
      <!--    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
      <!--    <ul class="dropdown-menu">-->
      <!--      <li><a href="#">Action</a></li>-->
      <!--      <li><a href="#">Another action</a></li>-->
      <!--      <li><a href="#">Something else here</a></li>-->
      <!--      <li role="separator" class="divider"></li>-->
      <!--      <li><a href="#">Separated link</a></li>-->
      <!--    </ul>-->
      <!--  </li>-->
      <!--</ul>-->
      
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  
 <%= render 'layouts/nav' %>
  

  <div class="pageContent container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum<br> Lorem ipsum Lorem ipsum</p>
  <p><%= link_to 'Sign Up', '' , class: 'btn btn-lg btn-default' %></p>
</div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="https://images.unsplash.com/photo-1437532437759-a0ce0535dfed?fit=crop&fm=jpg&h=700&q=80&w=1050" alt="...">

      <div class="caption">
        <h3>The recipe</h3>
        <p>...</p>
        <p><%= link_to 'Browser Recipe',recipes_path, class: "btn btn-primary", role: "button" %></p>
      </div>
      
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
  <div class="well col-md-8">
    <%= form_for(@recipe, html: { multipart: true }) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :summary %>
    <%= f.text_field :summary %>
    
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>    
    
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
    </span>
    
    <%= f.submit class: 'btn btn-success' %>
    <!-- f.submit(@recipe.new_record? ? 'Create Recipe' : 'Edit Recipe', class: 'btn btn-success') -->
    
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('#recipe_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 10) {
      alert('Maximum file size is 10MB. Please choose a smaller file');
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit recipe' %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: 'All Recipes' %>

<% @recipes.each do |recipe| %>
  <div class="row">
    
    <div class="col-md-2">
      <section class="chef_info center">
      <%= gravatar_for recipe.chef, size: 100 %>
      <h5>Chef Name: <%= recipe.chef.chefname %> </h5>
      </section>
    </div>
    
    <div class="col-md-6 well">
   <h4> <%= link_to recipe.name, recipe_path(recipe) %> </h4>
    <p> <%= recipe.summary %> </p>
    <p>
      <span class="quiet"><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span>
    </p>
    
    </div>
    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: '250x150', class: 'gravatar') if recipe.picture? %>
    </div>
  </div> 
  <hr>
      
<% end %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'Create a new recipe' %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>


<div class="row">
  <div class="col-md-4 pull-right center">
    <%= gravatar_for @recipe.chef, size: 200 %>
    <p>
      <h5>Brought to you by <%= @recipe.chef.chefname %> </h5>
    </p>
  </div>
  
  <div class="col-md-8">
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class:'gravatar') if @recipe.picture? %>
    </div>
    <div class="well">
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
    </div>
  </div>
</div>

<%= link_to 'Back', recipes_path , class: 'btn btn-primary' %>
 <%= link_to 'Edit', edit_recipe_path , class: 'btn btn-default' %> 

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
<h2><%= title %></h2>
<hr>
</p>